<?php

/**
 * Copyright (C) 2017 Entidad Pública Empresarial Red.es
 * 
 * This file is part of "dge_migrate (datos.gob.es)".
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_menu().
 */
function dge_migrate_menu() {
  $items['admin/config/dge/migrate/duplicate_file_usage'] = array(
    'title' => 'i18n config',
    'page callback' => 'dge_migrate_duplicate_file_usage',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK
  );
  $items['admin/config/dge/migrate/duplicate_file_usage_delete'] = array(
    'title' => 'i18n config',
    'page callback' => 'dge_migrate_duplicate_file_usage_delete',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function dge_migrate_duplicate_file_usage() {
  $result = db_select('file_usage', 'f')
    ->fields('f')
    ->execute();
  $response = array();
  foreach ($result as $usage) {
    $file =  file_load($usage->fid);
    file_usage_add($file, 'file', 'user', 1);
    $response[] = $file->fid;
  }

  if(function_exists('dpm'))
    dpm($response);
  return 'Done';

}


function dge_migrate_duplicate_file_usage_delete() {
  $result = db_select('file_usage', 'f')
    ->fields('f')
    ->condition('type','user')
    ->condition('id',1)
    ->execute();
  $response = array();
  foreach ($result as $usage) {
    $file =  file_load($usage->fid);
    file_usage_delete($file, 'file', 'user', 1, NULL);
    $response[] = $file->fid;
  }

  if(function_exists('dpm'))
    dpm($response);
  return 'Done';

}