<?php
/**
* Copyright (C) 2022 Entidad Pública Empresarial Red.es
* 
* This file is part of "dgef_menu (datos.gob.es)".
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 2 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file
 * dgef_menu.features.translations_ca.inc
 */

/**
 * Implements hook_translations_ca_defaults().
 */
function dgef_menu_translations_ca_defaults() {
  $translations = array();
  $translatables = array();
  $translations['ca:menu']['174a4602fe1632ef40d8ddb722c98ed6'] = array(
    'source' => 'FAQ',
    'context' => 'item:698:title',
    'location' => 'menu:item:698:title',
    'translation' => 'FAQ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('FAQ', array(), array('context' => 'item:698:title'));
  $translations['ca:menu']['19d792cbd4afb032a8031c42452fcd40'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:563:title',
    'location' => 'menu:item:563:title',
    'translation' => 'Empreses reutilitzadores',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:563:title'));
  $translations['ca:menu']['1c4920cbf9522bb22bf102e513ee5f30'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:646:title',
    'location' => 'menu:item:646:title',
    'translation' => 'Empreses reutilitzadores',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:646:title'));
  $translations['ca:menu']['29d6aa86f944772c811301282cd27295'] = array(
    'source' => 'FAQ',
    'context' => 'item:714:title',
    'location' => 'menu:item:714:title',
    'translation' => 'FAQ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('FAQ', array(), array('context' => 'item:714:title'));
  $translations['ca:menu']['339767640aceaceab6aaae1a45e2f8b4'] = array(
    'source' => 'Conjunto de datos',
    'context' => 'item:657:title',
    'location' => 'menu:item:657:title',
    'translation' => 'Conjunts de dades',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjunto de datos', array(), array('context' => 'item:657:title'));
  $translations['ca:menu']['65151156898802e9baef0d5a8cfd3b86'] = array(
    'source' => 'Mapa web',
    'context' => 'item:1064:title',
    'location' => 'menu:item:1064:title',
    'translation' => 'Mapa del lloc',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Mapa web', array(), array('context' => 'item:1064:title'));
  $translations['ca:menu']['73e3ac74b2264fdf8e5a73b1e4652cf0'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:649:title',
    'location' => 'menu:item:649:title',
    'translation' => 'Disponibilitat de dades',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:649:title'));
  $translations['ca:menu']['7753fe1c5d2f5190e55e2a0709cec2a8'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:572:title',
    'location' => 'menu:item:572:title',
    'translation' => 'Disponibilitat de dades',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:572:title'));
  $translations['ca:menu']['8e9a3f97650e0cba834f9590e400eac3'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:883:title',
    'location' => 'menu:item:883:title',
    'translation' => 'Empreses reutilitzadores',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:883:title'));
  $translations['ca:menu']['928ea601e24d5b5b246bd080d7ae706e'] = array(
    'source' => 'Gestión de usuarios',
    'context' => 'item:1065:title',
    'location' => 'menu:item:1065:title',
    'translation' => 'Gestió d\'usuaris',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Gestión de usuarios', array(), array('context' => 'item:1065:title'));
  $translations['ca:menu']['947e7d72ae05708285106683aa1aa1c3'] = array(
    'source' => 'Noticias',
    'context' => 'item:651:title',
    'location' => 'menu:item:651:title',
    'translation' => 'Notícies',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Noticias', array(), array('context' => 'item:651:title'));
  $translations['ca:menu']['9d8ec086508338e99bbfd55b6833c9f6'] = array(
    'source' => 'Iniciativas',
    'context' => 'item:1067:title',
    'location' => 'menu:item:1067:title',
    'translation' => 'Iniciatives',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Iniciativas', array(), array('context' => 'item:1067:title'));
  $translations['ca:menu']['b6efb781a6be4ae7145ad5f67676779a'] = array(
    'source' => 'Iniciativas',
    'context' => 'item:1120:title',
    'location' => 'menu:item:1120:title',
    'translation' => 'Iniciatives',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Iniciativas', array(), array('context' => 'item:1120:title'));
  $translations['ca:menu']['d52c27c798c9f2210daf85175ab2dc15'] = array(
    'source' => 'Datos no asignados',
    'context' => 'item:875:title',
    'location' => 'menu:item:875:title',
    'translation' => 'Dades no assignats',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Datos no asignados', array(), array('context' => 'item:875:title'));
  $translations['ca:menu']['e5d914da1479a33e6f4b3312af54fdc6'] = array(
    'source' => 'Mapa web',
    'context' => 'item:713:title',
    'location' => 'menu:item:713:title',
    'translation' => 'Mapa del lloc',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Mapa web', array(), array('context' => 'item:713:title'));
  $translations['ca:menu']['f043f3c38944d6e698bea197b0594e51'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:702:title',
    'location' => 'menu:item:702:title',
    'translation' => 'Disponibilitat de dades',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:702:title'));
  return $translations;
}
