<?php
/**
* Copyright (C) 2022 Entidad Pública Empresarial Red.es
* 
* This file is part of "dgef_menu (datos.gob.es)".
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 2 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file
 * dgef_menu.features.translations_en.inc
 */

/**
 * Implements hook_translations_en_defaults().
 */
function dgef_menu_translations_en_defaults() {
  $translations = array();
  $translatables = array();
  $translations['en:menu']['0e3646ebc1131e2d73afad1ae918a0cb'] = array(
    'source' => 'Catálogo de datos',
    'context' => 'item:865:title',
    'location' => 'menu:item:865:title',
    'translation' => 'Data catalog',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Catálogo de datos', array(), array('context' => 'item:865:title'));
  $translations['en:menu']['174a4602fe1632ef40d8ddb722c98ed6'] = array(
    'source' => 'FAQ',
    'context' => 'item:698:title',
    'location' => 'menu:item:698:title',
    'translation' => 'FAQ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('FAQ', array(), array('context' => 'item:698:title'));
  $translations['en:menu']['19d792cbd4afb032a8031c42452fcd40'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:563:title',
    'location' => 'menu:item:563:title',
    'translation' => 'Reuse companies',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:563:title'));
  $translations['en:menu']['1c4920cbf9522bb22bf102e513ee5f30'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:646:title',
    'location' => 'menu:item:646:title',
    'translation' => 'Reuse companies',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:646:title'));
  $translations['en:menu']['29d6aa86f944772c811301282cd27295'] = array(
    'source' => 'FAQ',
    'context' => 'item:714:title',
    'location' => 'menu:item:714:title',
    'translation' => 'FAQ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('FAQ', array(), array('context' => 'item:714:title'));
  $translations['en:menu']['339767640aceaceab6aaae1a45e2f8b4'] = array(
    'source' => 'Conjunto de datos',
    'context' => 'item:657:title',
    'location' => 'menu:item:657:title',
    'translation' => 'Datasets',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjunto de datos', array(), array('context' => 'item:657:title'));
  $translations['en:menu']['3de03656d7519876a3724c126a0ea52f'] = array(
    'source' => 'Catálogo de datos',
    'context' => 'item:554:title',
    'location' => 'menu:item:554:title',
    'translation' => 'Data catalog',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Catálogo de datos', array(), array('context' => 'item:554:title'));
  $translations['en:menu']['421e2214b9c1352180a688c9a2849f06'] = array(
    'source' => 'Entrevistas',
    'context' => 'item:567:title',
    'location' => 'menu:item:567:title',
    'translation' => 'Interviews',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Entrevistas', array(), array('context' => 'item:567:title'));
  $translations['en:menu']['49fbb84be4e1fbe2983c5eb792c5bde2'] = array(
    'source' => 'Asesoramiento y soporte',
    'context' => 'item:562:title',
    'location' => 'menu:item:562:title',
    'translation' => 'Advice and support',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Asesoramiento y soporte', array(), array('context' => 'item:562:title'));
  $translations['en:menu']['73e3ac74b2264fdf8e5a73b1e4652cf0'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:649:title',
    'location' => 'menu:item:649:title',
    'translation' => 'Data availability',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:649:title'));
  $translations['en:menu']['7753fe1c5d2f5190e55e2a0709cec2a8'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:572:title',
    'location' => 'menu:item:572:title',
    'translation' => 'Data availability',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:572:title'));
  $translations['en:menu']['83e8bd649076d47650601e8623eef97d'] = array(
    'source' => 'Entrevistas',
    'context' => 'item:654:title',
    'location' => 'menu:item:654:title',
    'translation' => 'Interviews',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Entrevistas', array(), array('context' => 'item:654:title'));
  $translations['en:menu']['8e9a3f97650e0cba834f9590e400eac3'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:883:title',
    'location' => 'menu:item:883:title',
    'translation' => 'Reuse companies',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:883:title'));
  $translations['en:menu']['928ea601e24d5b5b246bd080d7ae706e'] = array(
    'source' => 'Gestión de usuarios',
    'context' => 'item:1065:title',
    'location' => 'menu:item:1065:title',
    'translation' => 'User Management',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Gestión de usuarios', array(), array('context' => 'item:1065:title'));
  $translations['en:menu']['93dfa048d7e7459b12e3ee33d2dc2e49'] = array(
    'source' => 'Federador',
    'context' => 'item:704:title',
    'location' => 'menu:item:704:title',
    'translation' => 'Harvest',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Federador', array(), array('context' => 'item:704:title'));
  $translations['en:menu']['947e7d72ae05708285106683aa1aa1c3'] = array(
    'source' => 'Noticias',
    'context' => 'item:651:title',
    'location' => 'menu:item:651:title',
    'translation' => 'News',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Noticias', array(), array('context' => 'item:651:title'));
  $translations['en:menu']['99fb2915aa75e51fc35855689b827e8d'] = array(
    'source' => 'Cuadro de mando',
    'context' => 'item:558:title',
    'location' => 'menu:item:558:title',
    'translation' => 'Dashboard',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Cuadro de mando', array(), array('context' => 'item:558:title'));
  $translations['en:menu']['9d8ec086508338e99bbfd55b6833c9f6'] = array(
    'source' => 'Iniciativas',
    'context' => 'item:1067:title',
    'location' => 'menu:item:1067:title',
    'translation' => 'Initiatives',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Iniciativas', array(), array('context' => 'item:1067:title'));
  $translations['en:menu']['b6efb781a6be4ae7145ad5f67676779a'] = array(
    'source' => 'Iniciativas',
    'context' => 'item:1120:title',
    'location' => 'menu:item:1120:title',
    'translation' => 'Initiatives',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Iniciativas', array(), array('context' => 'item:1120:title'));
  $translations['en:menu']['b75bcd9d4c82e37e708067acc45b59d6'] = array(
    'source' => 'Conjuntos de Datos',
    'context' => 'item:638:title',
    'location' => 'menu:item:638:title',
    'translation' => 'Datasets',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjuntos de Datos', array(), array('context' => 'item:638:title'));
  $translations['en:menu']['b7ed925d9293e6890295b986815bd590'] = array(
    'source' => 'Mi cuadro de mando',
    'context' => 'item:705:title',
    'location' => 'menu:item:705:title',
    'translation' => 'Dashboard',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Mi cuadro de mando', array(), array('context' => 'item:705:title'));
  $translations['en:menu']['cdebcba4082a034384a641252a69ab62'] = array(
    'source' => 'Conjuntos de datos',
    'context' => 'item:708:title',
    'location' => 'menu:item:708:title',
    'translation' => 'Datasets',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjuntos de datos', array(), array('context' => 'item:708:title'));
  $translations['en:menu']['d52c27c798c9f2210daf85175ab2dc15'] = array(
    'source' => 'Datos no asignados',
    'context' => 'item:875:title',
    'location' => 'menu:item:875:title',
    'translation' => 'Unallocated data',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Datos no asignados', array(), array('context' => 'item:875:title'));
  $translations['en:menu']['e5bdabd84e08fe090284fa19d6521ffd'] = array(
    'source' => 'Buscar',
    'context' => 'item:866:title',
    'location' => 'menu:item:866:title',
    'translation' => 'Search',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Buscar', array(), array('context' => 'item:866:title'));
  $translations['en:menu']['f043f3c38944d6e698bea197b0594e51'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:702:title',
    'location' => 'menu:item:702:title',
    'translation' => 'Data availability',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:702:title'));
  $translations['en:menu']['ff25e93ed296ff506926a08a1ab7c14a'] = array(
    'source' => 'Publicador',
    'context' => 'item:864:title',
    'location' => 'menu:item:864:title',
    'translation' => 'Publisher',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Publicador', array(), array('context' => 'item:864:title'));
  return $translations;
}
