<?php
/**
* Copyright (C) 2022 Entidad Pública Empresarial Red.es
* 
* This file is part of "dgef_menu (datos.gob.es)".
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 2 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file
 * dgef_menu.features.translations_eu.inc
 */

/**
 * Implements hook_translations_eu_defaults().
 */
function dgef_menu_translations_eu_defaults() {
  $translations = array();
  $translatables = array();
  $translations['eu:menu']['0827ff9a3d00308455cfdf139be320dc'] = array(
    'source' => 'Informa sobre',
    'context' => 'item:555:title',
    'location' => 'menu:item:555:title',
    'translation' => 'Jakinarazi',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Informa sobre', array(), array('context' => 'item:555:title'));
  $translations['eu:menu']['0c4fef739253761c4d47126c6b131f48'] = array(
    'source' => 'Actualidad',
    'context' => 'item:860:title',
    'location' => 'menu:item:860:title',
    'translation' => 'Gaurkotasuna',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Actualidad', array(), array('context' => 'item:860:title'));
  $translations['eu:menu']['1133ad9c3be4872533a6a526d28de58f'] = array(
    'source' => 'Interactúa',
    'context' => 'item:539:title',
    'location' => 'menu:item:539:title',
    'translation' => 'Elkarreragin',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Interactúa', array(), array('context' => 'item:539:title'));
  $translations['eu:menu']['174a4602fe1632ef40d8ddb722c98ed6'] = array(
    'source' => 'FAQ',
    'context' => 'item:698:title',
    'location' => 'menu:item:698:title',
    'translation' => 'FAQ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('FAQ', array(), array('context' => 'item:698:title'));
  $translations['eu:menu']['19d792cbd4afb032a8031c42452fcd40'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:563:title',
    'location' => 'menu:item:563:title',
    'translation' => 'Enpresa berrerabiltzaileak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:563:title'));
  $translations['eu:menu']['1aa2bac2bab6fac7c49df6ff863978fc'] = array(
    'source' => 'Interactúa',
    'context' => 'item:861:title',
    'location' => 'menu:item:861:title',
    'translation' => 'Elkarreragin',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Interactúa', array(), array('context' => 'item:861:title'));
  $translations['eu:menu']['1c4920cbf9522bb22bf102e513ee5f30'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:646:title',
    'location' => 'menu:item:646:title',
    'translation' => 'Enpresa berrerabiltzaileak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:646:title'));
  $translations['eu:menu']['29d6aa86f944772c811301282cd27295'] = array(
    'source' => 'FAQ',
    'context' => 'item:714:title',
    'location' => 'menu:item:714:title',
    'translation' => 'FAQ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('FAQ', array(), array('context' => 'item:714:title'));
  $translations['eu:menu']['339767640aceaceab6aaae1a45e2f8b4'] = array(
    'source' => 'Conjunto de datos',
    'context' => 'item:657:title',
    'location' => 'menu:item:657:title',
    'translation' => 'Datu-multzoak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjunto de datos', array(), array('context' => 'item:657:title'));
  $translations['eu:menu']['49fbb84be4e1fbe2983c5eb792c5bde2'] = array(
    'source' => 'Asesoramiento y soporte',
    'context' => 'item:562:title',
    'location' => 'menu:item:562:title',
    'translation' => 'Aholkularitza eta laguntza',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Asesoramiento y soporte', array(), array('context' => 'item:562:title'));
  $translations['eu:menu']['65151156898802e9baef0d5a8cfd3b86'] = array(
    'source' => 'Mapa web',
    'context' => 'item:1064:title',
    'location' => 'menu:item:1064:title',
    'translation' => 'Webgunearen mapa',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Mapa web', array(), array('context' => 'item:1064:title'));
  $translations['eu:menu']['73e3ac74b2264fdf8e5a73b1e4652cf0'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:649:title',
    'location' => 'menu:item:649:title',
    'translation' => 'Datuen erabilgarritasuna',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:649:title'));
  $translations['eu:menu']['7753fe1c5d2f5190e55e2a0709cec2a8'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:572:title',
    'location' => 'menu:item:572:title',
    'translation' => 'Datuen erabilgarritasuna',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:572:title'));
  $translations['eu:menu']['8e9a3f97650e0cba834f9590e400eac3'] = array(
    'source' => 'Empresas reutilizadoras',
    'context' => 'item:883:title',
    'location' => 'menu:item:883:title',
    'translation' => 'Enpresa berrerabiltzaileak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Empresas reutilizadoras', array(), array('context' => 'item:883:title'));
  $translations['eu:menu']['928ea601e24d5b5b246bd080d7ae706e'] = array(
    'source' => 'Gestión de usuarios',
    'context' => 'item:1065:title',
    'location' => 'menu:item:1065:title',
    'translation' => 'Erabiltzaileak kudeatu',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Gestión de usuarios', array(), array('context' => 'item:1065:title'));
  $translations['eu:menu']['947e7d72ae05708285106683aa1aa1c3'] = array(
    'source' => 'Noticias',
    'context' => 'item:651:title',
    'location' => 'menu:item:651:title',
    'translation' => 'Berriak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Noticias', array(), array('context' => 'item:651:title'));
  $translations['eu:menu']['9d8ec086508338e99bbfd55b6833c9f6'] = array(
    'source' => 'Iniciativas',
    'context' => 'item:1067:title',
    'location' => 'menu:item:1067:title',
    'translation' => 'Ekimenak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Iniciativas', array(), array('context' => 'item:1067:title'));
  $translations['eu:menu']['a2617874ad4292e3b0e5023446ed4461'] = array(
    'source' => 'Actualidad',
    'context' => 'item:553:title',
    'location' => 'menu:item:553:title',
    'translation' => 'Gaurkotasuna',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Actualidad', array(), array('context' => 'item:553:title'));
  $translations['eu:menu']['b6efb781a6be4ae7145ad5f67676779a'] = array(
    'source' => 'Iniciativas',
    'context' => 'item:1120:title',
    'location' => 'menu:item:1120:title',
    'translation' => 'Ekimenak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Iniciativas', array(), array('context' => 'item:1120:title'));
  $translations['eu:menu']['b75bcd9d4c82e37e708067acc45b59d6'] = array(
    'source' => 'Conjuntos de Datos',
    'context' => 'item:638:title',
    'location' => 'menu:item:638:title',
    'translation' => 'Datu-multzoak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjuntos de Datos', array(), array('context' => 'item:638:title'));
  $translations['eu:menu']['cdebcba4082a034384a641252a69ab62'] = array(
    'source' => 'Conjuntos de datos',
    'context' => 'item:708:title',
    'location' => 'menu:item:708:title',
    'translation' => 'Datu-multzoak',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Conjuntos de datos', array(), array('context' => 'item:708:title'));
  $translations['eu:menu']['d52c27c798c9f2210daf85175ab2dc15'] = array(
    'source' => 'Datos no asignados',
    'context' => 'item:875:title',
    'location' => 'menu:item:875:title',
    'translation' => 'Datu esleitu gabe',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Datos no asignados', array(), array('context' => 'item:875:title'));
  $translations['eu:menu']['e5bdabd84e08fe090284fa19d6521ffd'] = array(
    'source' => 'Buscar',
    'context' => 'item:866:title',
    'location' => 'menu:item:866:title',
    'translation' => 'Bilatu',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Buscar', array(), array('context' => 'item:866:title'));
  $translations['eu:menu']['e5d914da1479a33e6f4b3312af54fdc6'] = array(
    'source' => 'Mapa web',
    'context' => 'item:713:title',
    'location' => 'menu:item:713:title',
    'translation' => 'Webgunearen mapa',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Mapa web', array(), array('context' => 'item:713:title'));
  $translations['eu:menu']['f043f3c38944d6e698bea197b0594e51'] = array(
    'source' => 'Disponibilidad de datos',
    'context' => 'item:702:title',
    'location' => 'menu:item:702:title',
    'translation' => 'Datuen erabilgarritasuna',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Disponibilidad de datos', array(), array('context' => 'item:702:title'));
  $translations['eu:menu']['ff25e93ed296ff506926a08a1ab7c14a'] = array(
    'source' => 'Publicador',
    'context' => 'item:864:title',
    'location' => 'menu:item:864:title',
    'translation' => 'Argitaratzailea',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Publicador', array(), array('context' => 'item:864:title'));
  return $translations;
}
