<?php

/**
 * Copyright (C) 2017 Entidad Pública Empresarial Red.es
 * 
 * This file is part of "dge_leaflet (datos.gob.es)".
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

define('GOOGLE_MAPS_API_KEY','AIzaSyDHouuNseoZO81sQhNuW3s41mvBy-3CpxI');

/**
 * Implements hook_libraries_info().
 *
 * Leaflet Search.
 */
function dge_leaflet_libraries_info() {

  $libraries['leaflet-search'] = array(
    'name' => 'Leaflet Search',
    'vendor url' => 'https://github.com/stefanocudini/leaflet-search',
    'download url' => 'https://github.com/stefanocudini/leaflet-search/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version":\s+"([\d+\.]*\d+)"/',
    ),
    'files' => array(
      'js' => array('src/leaflet-search.js'),
      'css' => array('src/leaflet-search.css'),
    ),
    'dependencies' => array('leaflet'),
  );
  $libraries['leaflet-fullscreen'] = array(
    'name' => 'Leaflet Fullscreen',
    'vendor url' => 'https://github.com/Leaflet/Leaflet.fullscreen',
    'download url' => 'https://github.com/Leaflet/Leaflet.fullscreen/archive/gh-pages.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version":\s+"([\d+\.]*\d+)"/',
    ),
    'files' => array(
      'js' => array('dist/Leaflet.fullscreen.min.js'),
      'css' => array('dist/leaflet.fullscreen.css'),
    ),
    'dependencies' => array('leaflet'),
  );

  return $libraries;
}

function dge_leaflet_get_baselayers() {
  $prot = '//';
  $attr_google = 'Map data &copy; <a target="attr" href="http://googlemaps.com">Google</a>';

  return array(
    'IGN Base' => array(
      'type' => 'wms',
      'urlTemplate' => 'http://www.ign.es/wms-inspire/ign-base',
      'options' => array(
        'attribution' => '© <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>',
        'layers' => 'IGNBaseTodo',
        'format' => 'image/png',
        'transparent' => false,
        'continuousWorld' => true,
      ),
      'layer_type' => 'base',
    ),
    'Google Maps' => array(
      'type' => 'google',
      // For retina displays we append '&style=high_dpi&w=512',
      'urlTemplate' => $prot . 'mt{s}.googleapis.com/vt?x={x}&y={y}&z={z}',
      'options' => array(
        'attribution' => $attr_google,
        'detectRetina' => TRUE,
        'subdomains' => array(0, 1, 2, 3),
      ),
      'layer_type' => 'base',
    ),
    /*'CartoCiudad' => array(
      'type' => 'wms',
      'urlTemplate' => 'http://www.cartociudad.es/wms/CARTOCIUDAD/CARTOCIUDAD',
      'options' => array(
        'attribution' => '<a href="http://www.cartociudad.es" target="_blank">CartoCiudad © Instituto Geográfico Nacional de España</a>',
        'layers' => array('Callejero','FondoUrbano'),
        'maxZoom' => 21,
        'format' => 'image/png',
        'transparent' => false,
        'version' => '1.3.0'
      ),
      'layer_type' => 'base',
    ),*/
  );
}

/**
 * Preprocess function for leaflet_more_maps.
 */
function dge_leaflet_leaflet_map_prebuild_alter(&$variables = NULL) {

  drupal_add_js(drupal_get_path('module', 'dge_leaflet').'/js/dge_leaflet.js');
  dge_leaflet_load_google_maps();
  libraries_load('leaflet-search');
  libraries_load('leaflet-fullscreen');
}

/**
 * @see hook_leaflet_map_info()
 */
function dge_leaflet_leaflet_map_info() {

  $default_settings = array(
    'attributionControl' => TRUE,
    'closePopupOnClick'  => TRUE,
    'doubleClickZoom'    => TRUE,
    'dragging'           => TRUE,
    'fadeAnimation'      => TRUE,
    'layerControl'       => FALSE,
    'maxZoom'            => 19,
    'minZoom'            => 0,
    'scrollWheelZoom'    => TRUE,
    'touchZoom'          => TRUE,
    'trackResize'        => TRUE,
    'zoomAnimation'      => TRUE,
    'zoomControl'        => TRUE,
  );

  // Two non-transparent layers, so entered as base_layers.
  $map_info['dge_leaflet'] = array(
    'label' => 'DGE Leaflet (zoom 0..21)',
    'description' => t('DGE Leaflet Layers'),
    'settings' => array('layerControl' => TRUE, 'maxZoom' => 21) + $default_settings,
    'layers' => dge_leaflet_get_baselayers(),
  );
  return $map_info;
}

/**
 * Implements hook_block_info().
 */
function dge_leaflet_block_info() {
  $blocks["dge_leaflet_baselayer_select"] = array(
    'info' => t('DGE Leaflet Baselayer Select'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dge_leaflet_block_view($delta) {
  if ($delta == 'dge_leaflet_baselayer_select') {
    $selectors = array();
    $i = 0;
    foreach(dge_leaflet_get_baselayers() as $name => $baselayer) {
      $selectors[] = l($name,'',array(
        'attributes'=>array(
          'data-leaflet-baselayer' => $i
        )
      ));
      $i++;
    }
    return array(
      'subject' => t('Layer selector'),
      'content' => theme('item_list',
        array(
          'items' => $selectors
        )),
    );
  }
}

/**
 * Implements hook_facet_items_alter().
 * @see facetapi_bonus
 */
function dge_leaflet_facet_items_alter(&$build, &$settings) {
  // Add icon leaflet
  if ($settings->facet == "field_initiative_admin_level") {
    $terms = taxonomy_term_load_multiple(array_keys($build));
    foreach($build as $key => $item) {
      if(isset($terms[$key]->field_initiative_icon[LANGUAGE_NONE][0]['fid'])) {
        $build[$key]["#html"] = true;
        $uri = $terms[$key]->field_initiative_icon[LANGUAGE_NONE][0]['uri'];
        $build[$key]['#markup'] = theme('image',array('path'=>$uri)) . $build[$key]['#markup'];
      }
    }
  }
}

function dge_leaflet_load_google_maps() {
  $googlemaps_api_key = GOOGLE_MAPS_API_KEY;
  drupal_add_js('https://maps.googleapis.com/maps/api/js?key='.$googlemaps_api_key.'&v=3&sensor=false', 'external');
}
