<?php

function dge_taxonomy_delete_taxonomy_term_delete($term) {
  db_delete('field_data_field_blog_tags')
    ->condition('field_blog_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_blog_tags')
    ->condition('field_blog_tags_tid', $term->tid)
    ->execute();

  db_delete('field_data_field_app_tags')
    ->condition('field_app_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_app_tags')
    ->condition('field_app_tags_tid', $term->tid)
    ->execute();

  db_delete('field_data_field_bulletin_tags')
    ->condition('field_bulletin_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_bulletin_tags')
    ->condition('field_bulletin_tags_tid', $term->tid)
    ->execute();

  db_delete('field_data_field_doc_tags')
    ->condition('field_doc_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_doc_tags')
    ->condition('field_doc_tags_tid', $term->tid)
    ->execute();

  db_delete('field_data_field_event_tags')
    ->condition('field_event_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_event_tags')
    ->condition('field_event_tags_tid', $term->tid)
    ->execute();

  db_delete('field_data_field_success_tags')
    ->condition('field_success_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_success_tags')
    ->condition('field_success_tags_tid', $term->tid)
    ->execute();

  db_delete('field_data_field_blog_blog_tags')
    ->condition('field_blog_blog_tags_tid', $term->tid)
    ->execute();

  db_delete('field_revision_field_blog_blog_tags')
    ->condition('field_blog_blog_tags_tid', $term->tid)
    ->execute();
}
