<?php

/**
 	* Copyright (C) 2022 Entidad Pública Empresarial Red.es
 	*
 	* This file is part of "dge_form_upgrades (datos.gob.es)".
 	*
 	* This program is free software: you can redistribute it and/or modify
 	* it under the terms of the GNU General Public License as published by
 	* the Free Software Foundation, either version 2 of the License, or
 	* (at your option) any later version.
 	*
 	* This program is distributed in the hope that it will be useful,
 	* but WITHOUT ANY WARRANTY; without even the implied warranty of
 	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 	* GNU General Public License for more details.
 	*
 	* You should have received a copy of the GNU General Public License
 	* along with this program. If not, see <http://www.gnu.org/licenses/>.

*/

/**
 * Implements hook_permission().
 */

function dge_form_upgrades_permission() {
  return array(
    'access form upgrades' => array(
      'title' => t('Administer DGE Form Upgrades'),
      'description' => t('Allow users to edit form description, link buttons and more'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function dge_form_upgrades_menu() {
  $items['admin/config/dge/form-descriptions'] = array(
    'title'             => 'Form Descriptions',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('dge_form_descriptions_admin_settings'),
    'access arguments'  => array('access form upgrades'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'dge_form_upgrades.admin.inc',
  );
  $items['admin/config/dge/form-links'] = array(
    'title'             => 'Form Links',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('dge_form_links_admin_settings'),
    'access arguments'  => array('access form upgrades'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'dge_form_upgrades.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dge_form_upgrades_form_node_form_alter(&$form, $form_state, $form_id) {
  global $user;
  global $language;
  //get current type
  $type = $form['#node']->type;
  //get enabled content types for displaying additional info
  $enabled_content_types = variable_get('dge_send_content_types', ADD_CONTENT_TYPES);

  if (in_array($type, $enabled_content_types) &&
       (!user_is_logged_in() || variable_get($type.'_all_access_form_description', 0) || variable_get($type.'_express_all_access_form_description', 0))) {

    //Get description for current language
    $defaults = array(
        'value' => '',
        'format' => 'full_html',
    );
    $content_type_description_field = variable_get($type.'_'.$language->language.'_form_description', $defaults);
    $express_content_type_description_field = variable_get($type.'_'.$language->language.'_express_form_description');
    $final_text = check_markup($content_type_description_field['value'], $content_type_description_field['format']);
    $express_final_text = check_markup($express_content_type_description_field['value'], $express_content_type_description_field['format']);
    //If empty text then get default language text
    if (empty($final_text) && $language->language != 'es') {
      $content_type_description_field = variable_get($type.'_es_form_description', $defaults);
      if (!empty($content_type_description_field['value'])) {
        $final_text = "<div lang='es' xml:lang='es'>".
                      check_markup($content_type_description_field['value'], $content_type_description_field['format'])
                      .'</div>';
      }
    }

    if (!empty($final_text)) {
      $form['info_form'] = array(
        '#markup' => '<div class="dge-form-description">'.$final_text.'</div>',
        '#weight' => -50,
      );
    }
    if (empty($express_final_text) && $language->language != 'es') {
      $express_content_type_description_field = variable_get($type.'_es_express_form_description', $defaults);
      if (!empty($express_content_type_description_field['value'])) {
        $express_final_text = "<div lang='es' xml:lang='es'>".
                      check_markup($express_content_type_description_field['value'], $express_content_type_description_field['format'])
                      .'</div>';
      }
    }
    $form['field_sender_terms_of_use']['und']['#title'] =strip_tags($express_final_text,'<a>');
    /*
    if (!empty($express_final_text) && isset( $form['field_sender_company'])) {
      $form['field_sender_company']['#suffix'] ='<div class="dge-form-description">'.$express_final_text.'</div>';
    } else if (!empty($express_final_text) && isset( $form['field_sender_phone'])){
      $form['field_sender_phone']['#suffix'] ='<div class="dge-form-description">'.$express_final_text.'</div>';
    }*/
  }

}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dge_form_upgrades_form_user_register_form_alter(&$form, $form_state, $form_id) {
  global $language;
  //Get description for current language
  $defaults = array(
    'value' => '',
    'format' => 'full_html',
  );
  $register_user_description_field = variable_get('registration_'.$language->language.'_form_description', $defaults);
  $final_text = check_markup($register_user_description_field['value'], $register_user_description_field['format']);
  //If empty text then get default language text
  if (empty($final_text) && $language->language != 'es') {
    $register_user_description_field = variable_get('registration_es_form_description', $defaults);
    if (!empty($register_user_description_field['value'])) {
      $final_text = "<div lang='es' xml:lang='es'>".
                    check_markup($register_user_description_field['value'], $register_user_description_field['format'])
                    .'</div>';
    }
  }
  if (!empty($final_text)) {
    $form['info_form'] = array(
      '#markup' => '<div class="dge-form-description">'.$final_text.'</div>',
      '#weight' => -50,
    );
  }
}
/**
 * Implements hook_form_alter().
 */
function dge_form_upgrades_form_alter(&$form, &$form_state, $form_id) {
    global $language;
  //Get description for current language
  $defaults = array(
    'value' => '',
    'format' => 'full_html',
  );


  if ($form_id == 'user_register_form') {
    $form['account']['mail']['#description'] = "<p>" . $form['account']['mail']['#description'] . "</p>";
    $form['account']['name']['#attributes']['required'] = 'required';
    $form['account']['mail']['#attributes']['required'] = 'required';
  }
  if ($form_id == 'webform_client_form_1' || $form_id == 'webform_client_form_2' || $form_id == 'webform_client_form_3' || $form_id == 'webform_client_form_4' || $form_id == 'webform_client_form_5') {
    $register_user_description_field = variable_get('contact_registration_'.$language->language.'_form_description', $defaults);
    $final_text = check_markup($register_user_description_field['value'], $register_user_description_field['format']);
    //If empty text then get default language text
    if (empty($final_text) && $language->language != 'es') {
      $register_user_description_field = variable_get('contact_registration_es_form_description', $defaults);
      if (!empty($register_user_description_field['value'])) {
        $final_text = "<div lang='es' xml:lang='es'>".
                      check_markup($register_user_description_field['value'], $register_user_description_field['format'])
                      .'</div>';
      }
    }
    if (!empty($final_text)) {
$form['submitted']['acepto_las_condiciones_de_servicio']['#options'][1] =strip_tags($final_text,'<a>');
    }
   }
   if($form_id == 'simplenews_block_form_21'){
 $terms_anchor = variable_get('dge_send_content_terms_of_use_anchor',t('the express consent'));
  $terms_link = 'http://www.red.es/redes/es/quienes-somos/protecci%C3%B3n-de-datos-de-car%C3%A1cter-personal';
  $terms_anchor_link = l($terms_anchor, $terms_link);
  //$terms_anchor_link = l($terms_anchor, $terms_link, array('attributes' => array('class' => 'terms-of-use')));
 $terms_label = variable_get('dge_send_content_terms_of_use_text', t('I read and accept !terms_anchor_link', array('!terms_anchor_link' => $terms_anchor_link)));
   //$terms_label = t("I read and accept the express consent.");
   $form['condiciones']['#title']=$terms_label;
   $form['condiciones']['#attributes']['required']='required';

    $boletin_user_description_field = variable_get('boletin_registration_'.$language->language.'_form_description', $defaults);
    $boletin_final_text = check_markup($boletin_user_description_field['value'], $boletin_user_description_field['format']);
    // var_dump(check_markup($boletin_user_description_field['value'], $boletin_user_description_field['format']));
    //If empty text then get default language text
    if (empty($boletin_final_text) && $language->language != 'es') {
      $boletin_user_description_field = variable_get('boletin_registration_es_form_description', $defaults);
      if (!empty($boletin_user_description_field['value'])) {
        $boletin_final_text = "<div lang='es' xml:lang='es'>".
                      check_markup($boletin_user_description_field['value'], $boletin_user_description_field['format'])
                      .'</div>';
      }
    }
    if (!empty($boletin_final_text)) {
      $form['condiciones']['#title']= "<span class='terms'>".$boletin_final_text."</span>";
    }
    if(isset($_POST['action2'])){
		if($_POST['action2'] === 'unsubscribe'){
		  unset($form['condiciones']['#attributes']['required']);
		  unset($form['condiciones']['#required']);
		 }
	}
   }
    /* SDA-360 MODIFICANDO FORMULARIOS PARA EL REQUEST */
    if($form_id == 'initiative_node_form'){
        $theme_path = drupal_get_path('theme', 'dge_theme');
        $form['#attached']['js'][] = $theme_path . '/js/accesibility.js';
        $form['title']['#attributes']['required'] = 'required';
        $form['field_initiative_organization']['und'][0]['value']['#attributes']['required'] = 'required';
        $form['field_sender_terms_of_use']['und']['#attributes']['required'] = 'required';
        $form['field_initiative_link']['und']['#attributes']['required'] = 'required';
    }
    if($form_id == 'app_node_form'){
        $form['title']['#attributes']['required'] = 'required';
        $form['body']['und'][0]['#attributes']['required'] = 'required';
        $form['field_sender_terms_of_use']['und']['#attributes']['required'] = 'required';
        $form['field_app_publish_date']['label'] = null;
    }
    if($form_id == 'success_node_form'){
        $form['field_sender_terms_of_use']['und']['#attributes']['required'] = 'required';
    }

 }


/**
 * Implements hook_form_profile2_form_alter().
 */
function dge_form_upgrades_form_profile2_form_alter(&$form, &$form_state) {
  $form['profile_main']['field_name_contact']['und'][0]['value']['#attributes']['required'] = 'required';
  $form['profile_main']['field_phone_contact']['und'][0]['value']['#attributes']['required'] = 'required';
  $form['profile_main']['field_surname_contact']['und'][0]['value']['#attributes']['required'] = 'required';

  if ($form['profile_agency_data']['field_position_agency']) {
    $form['profile_agency_data']['field_position_agency']['und'][0]['value']['#attributes']['required'] = 'required';
    $form['profile_agency_data']['field_terms_service']['und'][0]['#attributes']['required'] = 'required';
    $form['profile_agency_data']['field_terms_service']['und'][0]['#default_value'][0] = FALSE;

  }


  global $language;
  //Get description for current language
  $defaults = array(
    'value' => '',
    'format' => 'full_html',
  );
  $express_register_user_description_field = variable_get('express_registration_'.$language->language.'_form_description', $defaults);
  $express_final_text = check_markup($express_register_user_description_field['value'], $express_register_user_description_field['format']);
  //If empty text then get default language text
  if (empty($express_final_text) && $language->language != 'es') {
    $express_register_user_description_field = variable_get('express_registration_es_form_description', $defaults);
    if (!empty($express_register_user_description_field['value'])) {
      $express_final_text = "<div lang='es' xml:lang='es'>".
                    check_markup($express_register_user_description_field['value'], $express_register_user_description_field['format'])
                    .'</div>';
    }
  }
  if ($form['profile_agency_data']['field_terms_service']) {
  $form['profile_agency_data']['field_terms_service']['und'][0]['#title'] =strip_tags($express_final_text,'<a>');  }


}

/**
 * Implements hook_block_info().
 */
function dge_form_upgrades_block_info() {
  $blocks = array();

  foreach(variable_get('dge_send_content_types', ADD_CONTENT_TYPES) as $type) {
    $blocks['dge_form_upd_link_'.$type] = array(
      'info' => t('DGE Add Content !type button',array('!type' => $type)),
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dge_form_upgrades_block_view($delta = '') {
  $block = array();
  if(strstr($delta,'dge_form_upd_link_') !== false){
    $type = str_replace('dge_form_upd_link_', '', $delta);
    $block['subject'] = t('Add Content @type Link Button', array('@type' => ucfirst($type)));
    $block['content'] = dge_form_upgrades_button_block($type);
  }
  return $block;
}

/**
 * Content of Node Add button block
 */
function dge_form_upgrades_button_block($type) {
  $text_link = variable_get('dge_form_links_title_'.$type, '');
  $url_link = variable_get('dge_form_links_url_'.$type, '');

  //If URL Link is empty get value from dge_access_node
  if (empty($url_link)) {
    $url_link = variable_get('dge_access_node_add_redirect_'.$type,'');
  }
  if (empty($url_link)) {
    watchdog('dge_form_upgrades', 'ADD BUTTON: No se ha configurado una URL para el tipo de contenido @type', array('@type' => $type), WATCHDOG_WARNING);
    return '';
  }
  $item = menu_get_item($url_link);
  //Check if the user can access to the page
  if ($item && $item['access']) {
    if (! variable_get('dge_form_links_'.$type.'button_hidden', false)) {
      return theme('dge_form_upgrades_link', array( 'type' => $type, 'text_link' => $text_link, 'url_link' => $url_link, 'wrapper' => TRUE ));
    } else {
      $button = theme('dge_form_upgrades_link', array( 'type' => $type, 'text_link' => $text_link, 'url_link' => $url_link ));
      dge_basic_add_additional_button($button, -10);
    }
  } else {
    watchdog('dge_form_upgrades', 'ADD BUTTON: El usuario no puede acceder a la URL @url_link', array('@url_link' => $url_link), WATCHDOG_WARNING);
    return '';
  }
}


/**
 * Implements hook_theme().
 */
function dge_form_upgrades_theme() {
  return array(
    'dge_form_upgrades_link' => array(
      'variables' => array('type' => NULL, 'text_link' => NULL, 'url_link' => NULL, 'wrapper' => FALSE),
    ),
  );
}

/**
 * THEME theme_dge_form_upgrades_link.
 */
function theme_dge_form_upgrades_link($variables) {
  $output = '';
  $text_link = $variables['text_link'];
  if (empty($text_link)) {
    $type_title = '';
    if (module_exists('i18n_node')) {
      $type_title = i18n_string_translate(
         array('node', 'type', $variables['type'], 'name'),
         node_type_get_name($variables['type']),
         array('sanitize' => FALSE, 'langcode' => 'en'));
      $text_link = t('Report a new'.$type_title);
    } else {
      $node_type = node_type_load($variables['type']);
      $type_title = $node_type->name;
      $text_link = t('Añadir '.$type_title);
    }
  } else {
    $text_link = t($text_link);
  }
  $output .= '<a href="'.url($variables['url_link']).'" title="'.$text_link.'" ';
  $output .= 'class="add-icon dge-type-add-link dge-type-add-link-'.$variables['type'].'">';
  $output .= $text_link.'</a>';

  if (!empty($variables['wrapper']))
    $output = '<div class="dge-content-type-add-link dge-content-type-add-link-'.$variables['type'].'">'.$output.'</div>';

  return $output;
}


