<?php

/**
 	* Copyright (C) 2022 Entidad Pública Empresarial Red.es
 	*
 	* This file is part of "dge_devel (datos.gob.es)".
 	*
 	* This program is free software: you can redistribute it and/or modify
 	* it under the terms of the GNU General Public License as published by
 	* the Free Software Foundation, either version 2 of the License, or
 	* (at your option) any later version.
 	*
 	* This program is distributed in the hope that it will be useful,
 	* but WITHOUT ANY WARRANTY; without even the implied warranty of
 	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 	* GNU General Public License for more details.
 	*
 	* You should have received a copy of the GNU General Public License
 	* along with this program. If not, see <http://www.gnu.org/licenses/>.

*/

/**
 * Implements hook_menu().
 */
function dge_devel_menu() {
  $items['admin/config/development/dge_devel'] = array(
    'title'             => 'DGE Web server logging and alerts',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('dge_devel_admin_settings'),
    'access arguments'  => array('administer site configuration'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'dge_devel.admin.inc',
  );
      $items['admin/config/development/app_convert'] = array(
    'title'             => 'DGE Web server logging and alerts',
    'page callback'     => 'dge_devel_app_import_date',
    'access arguments'  => array('administer site configuration'),
    'type'              => MENU_CALLBACK,
    'file'              => 'dge_devel.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_watchdog().
 * If it is enabled then Drupal logs messages marked as debug (severity level WATCHDOG_DEBUG)
 *
 * @param $log
 *   An associative array containing the following keys:
 *   - type: The type of message for this entry.
 *   - user: The user object for the user who was logged in when the event
 *     happened.
 *   - uid: The user ID for the user who was logged in when the event happened.
 *   - request_uri: The request URI for the page the event happened in.
 *   - referer: The page that referred the user to the page where the event
 *     occurred.
 *   - ip: The IP address where the request for the page came from.
 *   - timestamp: The UNIX timestamp of the date/time the event occurred.
 *   - severity: The severity of the message; one of the following values as
 *     defined in @link http://www.faqs.org/rfcs/rfc3164.html RFC 3164: @endlink
 *     - WATCHDOG_EMERGENCY: Emergency, system is unusable.
 *     - WATCHDOG_ALERT: Alert, action must be taken immediately.
 *     - WATCHDOG_CRITICAL: Critical conditions.
 *     - WATCHDOG_ERROR: Error conditions.
 *     - WATCHDOG_WARNING: Warning conditions.
 *     - WATCHDOG_NOTICE: Normal but significant conditions.
 *     - WATCHDOG_INFO: Informational messages.
 *     - WATCHDOG_DEBUG: Debug-level messages.
 *   - link: An optional link provided by the module that called the watchdog()
 *     function.
 *   - message: The text of the message to be logged. Variables in the message
 *     are indicated by using placeholder strings alongside the variables
 *     argument to declare the value of the placeholders. See t() for
 *     documentation on how the message and variable parameters interact.
 *   - variables: An array of variables to be inserted into the message on
 *     display. Will be NULL or missing if a message is already translated or if
 *     the message is not possible to translate.
 */
function dge_devel_watchdog($log) {
  if($log['severity'] == WATCHDOG_DEBUG) {
    if (variable_get('dge_devel_debug', FALSE)) {
      if (!is_array($log['variables'])) {
        $log['variables'] = array();
      }
      error_log(serialize($log));

      if(variable_get('dge_devel_debug_print', FALSE)) {
        $vars = array($log['type'],isset($log['variables']) ? $log['variables'] : $log);
        if(function_exists('dpm')) {
          dpm($vars);
        }
        else {
          var_dump($vars);
        }
      }
    }
    else {
      return;
    }
  }

}
