<?php

/**
 	* Copyright (C) 2022 Entidad Pública Empresarial Red.es
 	*
 	* This file is part of "dge_newsletter (datos.gob.es)".
 	*
 	* This program is free software: you can redistribute it and/or modify
 	* it under the terms of the GNU General Public License as published by
 	* the Free Software Foundation, either version 2 of the License, or
 	* (at your option) any later version.
 	*
 	* This program is distributed in the hope that it will be useful,
 	* but WITHOUT ANY WARRANTY; without even the implied warranty of
 	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 	* GNU General Public License for more details.
 	*
 	* You should have received a copy of the GNU General Public License
 	* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

define('DGE_NEWSLETTER_SEND_TEST_LIST', 57394);
define('DGE_NEWSLETTER_SEND_SENDINBLUE',44444);

function dge_newsletter_libraries_info() {

  $libraries['dge_sendinblue_php_client'] = array(
    'name' => 'DGE SENDINBLUE PHP client',
    'version arguments' => array(
      'file' => 'README.txt',
      'pattern' => '/API Version: ((\d+)\.(\d+))/',
    ),
    'files' => array(
      'php' => array('DgeSendInBlueClient.php'),
    )
  );

  return $libraries;
}
// libraries_load('dge_sendinblue_php_client');
//     if ($library = libraries_detect('dge_sendinblue_php_client') && !empty($library['installed'])) {
//       drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'),'error');
//     }
/**
* Implements hook_menu().
*/
function dge_newsletter_menu() {
  $items['admin/config/dge/newsletter'] = array(
    'title' => t('Newsletters and SendInBlue settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dge_newsletter_admin_settings'),
    'access arguments' => array('administer simplenews settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'dge_newsletter.admin.inc',
  );

  $items['boletines/%/mail-view'] = array(
    'title' => t('Newsletter'),
    'page callback' => 'dge_newsletter_mail_presentation',
    'page arguments' => array(1),
    'access arguments' => array('create bulletin content'),
    'type' => MENU_CALLBACK,
  );

  $items['formulario-de-baja'] = array(
    'title' => t('Formulario de baja'),
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('dge_newsletter_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function dge_newsletter_form($form, &$form_state) {

  $form['#attributes'] = array('class' => 'dge-newsletter-sendinblue-form');
  $form['#prefix'] = '<div id="sib-container">';
  $form['#suffix'] = '</div>';
  $form['title'] = array(
    '#type' => 'markup',
    '#markup' => '<h2>' . t('Subscription cancellation') . '</h2>',
    '#prefix' => '<div class="sib-form-block">',
    '#suffix' => '</div>',
  );

  $form['description'] = array(
    '#type' => 'markup',
    '#markup' => '<p>' . t('Click on «Unsubscribe» to unsubscribe from the Datos.gob Newsletter:') . '</p>',
    '#attributes' => array('class' => array('test-class')),
    '#prefix' => '<div class="sib-form-block"><div class"sib-text-form-block">',
    '#suffix' => '</div></div>',
  );

  $form['email'] =  array(
    '#title' => t('Enter your email address to unsubscribe'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Enter your email address to subscribe. Ex: abc@xyz.com'),
    '#attributes' => array('class' => array('test-class')),
    '#prefix' => '<div class="sib-form-block">',
    '#suffix' => '</div>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel the subscription'),
    '#prefix' => '<div class="sib-form-block">',
    '#suffix' => '</div>',
    '#submit' => array('_dge_newsletter_sendinblue_form_submit')
  );

  $form['#validate'][] = '_dge_newsletter_sendinblue_form_validate';

  return $form;
}


function _dge_newsletter_sendinblue_form_validate($form, &$form_state) {
  libraries_load('dge_sendinblue_php_client');
  if ($library = libraries_detect('dge_sendinblue_php_client') && ! empty($library['installed'])) {
    drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'), 'error');
  }
  if (!filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL)) {
    drupal_set_message(t('Enter a valid email. Ex: abc@xyz.com'), 'error');
  } else {
      try {
        $sendinblue = new DgeSendInBlueClient(variable_get('dge_newsletter_sendinblue_api_key'), variable_get('dge_newsletter_sendinblue_list_id'));
        $contacts = $sendinblue->getContactsFromList();
        if(!in_array($form_state['values']['email'], $contacts)) {
          drupal_set_message(t('The email entered is not subscribed to the datos.gob newsletter'), 'error');
        }
      } catch (Exception $e) {

      }
  }
}

function _dge_newsletter_sendinblue_form_submit($form, &$form_state) {

  $subscriber = $form_state['values']['email'];
  libraries_load('dge_sendinblue_php_client');
  if ($library = libraries_detect('dge_sendinblue_php_client') && ! empty($library['installed'])) {
    drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'), 'error');
  }
  try {
    $sendinblue = new DgeSendInBlueClient(variable_get('dge_newsletter_sendinblue_api_key'), variable_get('dge_newsletter_sendinblue_list_id'));
    $sendinblue->removeContactFromList($subscriber);
    drupal_set_message(t('You have successfully unsubscribed from the datos.gob newsletter'), 'status');
    if (variable_get('dge_newsletter_sendinblue_from')) {
      watchdog('dge_newsletter', t('Envio de email para dar de baja a @user del newsletter'),
        array('@user' => $subscriber), WATCHDOG_INFO);

      $params = array(
        'body' => t(variable_get('dge_newsletter_unsuscribe_email_content')),
        'subject' => t(variable_get('dge_newsletter_unsuscribe_email_subject')),
        'langcode' => $GLOBALS['language']->language,
        'headers' => array(
          'Bcc' => variable_get('dge_newsletter_unsuscribe_send_email'),
        ),
        //'dge_subscriptors' => $subscriber,
      );
      $mail = drupal_mail(
        'dge_newsletter',
        'unsubscribe',
        $subscriber,
        language_default(),
        $params,
        variable_get('dge_newsletter_unsuscribe_send_email')
      );

      if ($mail['result'] == FALSE) {
        watchdog('maillog', t('Fallo al eliminar de la lista al usuario @user'),
          array('@user' => $subscriber), WATCHDOG_ERROR);
      }
    } else {
      watchdog('maillog', 'SendInBlue: Sin configurar. No se ha enviado el correo de baja de @user de la lista',
        array('@user' => $subscriber), WATCHDOG_INFO);
    }
  } catch (Exception $e) {

  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dge_newsletter_form_simplenews_node_tab_send_form_alter(&$form, $form_state, $form_id) {
  //$sympa_mailbox = variable_get('dge_newsletter_sympa_mail_box');
  //$sympa_email = variable_get('dge_newsletter_sympa_from');

  // Se quita la opcion de envio normal (Que mandaria el correo a todos los usuarios suscritos)
  /*if (isset($sympa_mailbox) && isset($sympa_email)) {
    if (! variable_get('dge_newsletter_sympa_send_email', 0)) {

      $form['simplenews']['send']['#options'] = array ( SIMPLENEWS_COMMAND_SEND_TEST => 'Enviar el bolet&iacute;n a la Direcci&oacute;n de env&iacute;o del bolet&iacute;n' );
    } else {*/


      // Enable new send processing action
      $form['simplenews']['send']['#options'] = array ( SIMPLENEWS_COMMAND_SEND_TEST => 'Enviar un boletín de prueba a la Direcci&oacute;n de env&iacute;o del bolet&iacute;n',
                                                      DGE_NEWSLETTER_SEND_TEST_LIST =>  'Enviar el bolet&iacute;n a la lista de pruebas de SendInBlue' );
      $form['#submit'][]='dge_newsletter_form_simplenews_send_sympa';

      if (isset($form['simplenews']['test_address']) && $form['simplenews']['test_address']['#type'] != 'value') {
        $form['simplenews']['test_address']['#states'] =array (
             'visible' => array(
                ':input[name="simplenews[send]"]' => array('value' => SIMPLENEWS_COMMAND_SEND_TEST),
            ),
        );
      }
    //}

    libraries_load('dge_sendinblue_php_client');
        if ($library = libraries_detect('dge_sendinblue_php_client') && ! empty($library['installed'])) {
            drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'), 'error');
        }
        if (variable_get('dge_newsletter_sendinblue_api_key') && variable_get('dge_newsletter_sendinblue_list_id')) {
            try {
                $client = new  DgeSendInBlueClient(variable_get('dge_newsletter_sendinblue_api_key'), variable_get('dge_newsletter_sendinblue_list_id'));

               $form['simplenews']['send']['#options'][DGE_NEWSLETTER_SEND_SENDINBLUE]='Enviar el boletín a los suscriptores con SendInBlue';

            } catch (Exception $e) {

            }
        }



    $form['simplenews']['send']['#default_value'] = SIMPLENEWS_COMMAND_SEND_TEST;
    $form['simplenews']['indicaciones'] = array (
      '#markup' => '<p>Los boletines est&aacute;n integrados con <strong>SendInBlue</strong> El <strong>env&iacute;o normal</strong> ha sido <strong>deshabilitado</strong> para no realizar un env&iacute;o est&aacute;ndar a los usuarios suscritos directamente por error.</p>',
      '#weight' => -50
    );
    if (isset($form['simplenews']['test_address']) && $form['simplenews']['test_address']['#type'] != 'value') {
      $form['simplenews']['test_address']['#title'] = 'Direcci&oacute;n de env&iacute;o del bolet&iacute;n';
    } else {
      $form['simplenews']['test_address'] = array (
        '#markup' => '<p><strong>Direcci&oacute;n de env&iacute;o: </strong> '.variable_get('simplenews_test_address', $address_default) . ' <br/>(Campo de configuración de Simplenews <strong>"'. t('Email address').'"</strong>).</p>',
        '#weight' => 50
      );
    }
  //}
}

// Send mail with SYMPA
function dge_newsletter_form_simplenews_send_sympa($form, &$form_state) {
  // dpm($form_state);
  if(isset($form_state['values']['simplenews']['send']) && isset($form_state['values']['nid']) &&
    (($form_state['values']['simplenews']['send'] == DGE_NEWSLETTER_SEND_SENDINBLUE) || ($form_state['values']['simplenews']['send'] == DGE_NEWSLETTER_SEND_TEST_LIST))) {
    if($form_state['values']['simplenews']['send'] == DGE_NEWSLETTER_SEND_SENDINBLUE) {
      $list_id = variable_get('dge_newsletter_sendinblue_list_id');
      $string = "Newsletter sent to subscriptors by SendInBlue.";
    } else {
      $list_id = variable_get('dge_newsletter_sendinblue_test_list_id');
      $string = "Newsletter sent to TEST list by SendInBlue.";
    }
    libraries_load('dge_sendinblue_php_client');
    if ($library = libraries_detect('dge_sendinblue_php_client') && ! empty($library['installed'])) {
        drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'), 'error');
    }
    if (variable_get('dge_newsletter_sendinblue_api_key') && variable_get('dge_newsletter_sendinblue_list_id')) {
        if(!variable_get('dge_newsletter_sendinblue_from')){
          drupal_set_message('Es necesario configurar el campo "From email" de SendInBlue en: <a href=" . url(/admin/config/dge/newsletter) . ">Configuracion de boletín</a> ', 'error');
          return;
        }
        try {
            $client = new  DgeSendInBlueClient(variable_get('dge_newsletter_sendinblue_api_key'), $list_id);
            module_load_include('inc', 'simplenews', 'includes/simplenews.mail');

            $node = node_load($form_state['values']['nid']);

            // The source expects a subscriber object with mail and language set.
            $subscriber = new stdClass();
            $subscriber->uid = 0;
            $subscriber->mail = variable_get('dge_newsletter_sendinblue_from');
            $subscriber->language = $GLOBALS['language']->language;
            $source = new SimplenewsSourceNode($node, $subscriber);
            $source->setKey('test');
            // $message['subject'] = $source->getSubject();
            // $message['body']['body'] = $source->getBody();
            // $message['body']['footer'] = $source->getFooter();
            // dpm($source->getBody());
            $cam=$client->createEmailCampaign(variable_get('dge_newsletter_sendinblue_from'),$node->title,$source->getSubject(),$source->getBody(),'If you wish to unsubscribe from our newsletter, click {here}');
            $client->sendEmailCampaignNow($cam->getId());
            drupal_set_message(t($string));
            watchdog('maillog', 'Boletín envíado', WATCHDOG_INFO);

        } catch (Exception $e) {

        drupal_set_message($e->getmessage(), 'error');

        }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dge_newsletter_form_simplenews_subscriptions_page_form_alter(&$form, $form_state, $form_id) {
  if (empty($form['#attributes'])) {
    $form['#attributes'] = array();
  }
  $form['#attributes']['class'] = array('dge-form');

}


 /*/**
 * Implements hook_simplenews_subscribe_user().
 */
/*function dge_newsletter_simplenews_subscribe_user($subscriber, $subscription) {

  libraries_load('dge_sendinblue_php_client');
  if ($library = libraries_detect('dge_sendinblue_php_client') && !empty($library['installed'])) {
    drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'),'error');
  }

  try{

    $client = new  DgeSendInBlueClient(variable_get('dge_newsletter_sendinblue_api_key'), variable_get('dge_newsletter_sendinblue_list_id'));
    $client->addSubscriptorsToList($subscriber->mail);
    watchdog('dge_newsletter', 'SendInBlue: @user añadido a la lista',    array('@user' => $subscriber->mail), WATCHDOG_INFO);
  }catch(Exception $e){
    watchdog('dge_newsletter', 'SendInBlue:'.$e->getmessage(), WATCHDOG_ERROR);
  }

  //correspondiente al registro de user en sympa
  if (variable_get('dge_newsletter_sympa_mail_box')) {
    watchdog('dge_newsletter', 'SYMPA: Envio de email para suscribir a @user al newsletter',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);

    $params = array(
       'dge_subscriptors' => $subscriber->mail,
    );

    $mail = drupal_mail('dge_newsletter', 'subscribe',
                       variable_get('dge_newsletter_sympa_mail_box'),
                       language_default(),
                       $params,
                       variable_get('dge_newsletter_sympa_from'));

    if ($mail['result'] == FALSE) {
      watchdog('dge_newsletter', 'SYMPA: Fallo al incluir al usuario @user a la lista',
           array('@user' => $subscriber->mail), WATCHDOG_ERROR);
    }
  } else {
    watchdog('dge_newsletter', 'SYMPA: Sin configurar. No se ha enviado el correo de subscripcion a @user a la lista',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);
  }
}*/

 /*/**
 * Implements hook_simplenews_unsubscribe_user().
 *//*
function dge_newsletter_simplenews_unsubscribe_user($subscriber, $subscription) {
  libraries_load('dge_sendinblue_php_client');
  if ($library = libraries_detect('dge_sendinblue_php_client') && !empty($library['installed'])) {
    drupal_set_message(t('DGE SENDINBLUE PHP Client is not installed'),'error');
  }

  try{

    $client = new  DgeSendInBlueClient(variable_get('dge_newsletter_sendinblue_api_key'), variable_get('dge_newsletter_sendinblue_list_id'));
    $client->removecontactfromlist($subscriber->mail);
    watchdog('dge_newsletter', 'SendInBlue: @user se eliminó a la lista',    array('@user' => $subscriber->mail), WATCHDOG_INFO);
  }catch(Exception $e){
    watchdog('dge_newsletter', 'SendInBlue:'.$e->getmessage(), WATCHDOG_ERROR);
  }


  if (variable_get('dge_newsletter_sympa_mail_box')) {
    watchdog('dge_newsletter', 'SYMPA: Envio de email para dar de baja a @user del newsletter',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);

    $params = array(
       'dge_subscriptors' => $subscriber->mail,
    );
    $mail = drupal_mail('dge_newsletter', 'unsubscribe',
                       variable_get('dge_newsletter_sympa_mail_box'),
                       language_default(),
                       $params,
                       variable_get('dge_newsletter_sympa_from'));

    if ($mail['result'] == FALSE) {
      watchdog('dge_newsletter', 'SYMPA: Fallo al eliminar de la lista al usuario @user',
               array('@user' => $subscriber->mail), WATCHDOG_ERROR);
    }
  } else {
    watchdog('dge_newsletter', 'SYMPA: Sin configurar. No se ha enviado el correo de baja de @user de la lista',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);
  }

}*/

function dge_newsletter_mail($key, &$message, $params) {

  switch ($key) {
    case 'unsubscribe':
      /*$sympa_command = variable_get('dge_newsletter_sympa_unsubscription_command',
                       'c %email');
      $sympa_command = str_replace('%email', $params['dge_subscriptors'], $sympa_command);*/
      $headers['headers'] = array(
        'Bcc' => variable_get('dge_newsletter_unsuscribe_send_email'),
      );
      $message['subject'] = t(variable_get('dge_newsletter_unsuscribe_email_subject'));
      $message['body'][] = t(variable_get('dge_newsletter_unsuscribe_email_content'));
      break;
    case 'send':
      $source = $params['simplenews_source'];
      $headers = $source->getHeaders($message['headers']);
      //Force SYMPA FROM
      $headers['From'] = $message['headers']['From'];
      $message['headers'] = $headers;
      $message['subject'] = $source->getSubject();
      $message['body']['body'] = $source->getBody();
      $message['body']['footer'] = $source->getFooter();
      // Optional params for HTML mails.
      if ($source->getFormat() == 'html') {
        $message['params']['plain'] = NULL;
        $message['params']['plaintext'] = $source->getPlainBody() . "\n" . $source->getPlainFooter();
        $message['params']['attachments'] = $source->getAttachments();
      } else {
        $message['params']['plain'] = TRUE;
      }
      break;
  }
}

/*function dge_newsletter_mail_presentation($nid) {
  if (is_numeric($nid)) {
    $node = node_load($nid);
    if ($node && $node->type == 'bulletin') {
      drupal_set_title($node->title);
      $build = node_view($node, 'email_html');
      unset($build['#theme']);
    }
  }

  if (!isset($build)) {
    drupal_not_found();
    exit();
  }

  if (isset($node->field_simplenews_term['es'][0]['tid'])) {
    $category = $node->field_simplenews_term['es'][0]['tid'];
  } elseif (isset($node->field_simplenews_term['und'][0]['tid'])) {
    $category = $node->field_simplenews_term['und'][0]['tid'];
  }
  $category = taxonomy_term_load($category);

  //Generate email
  $body = theme('simplenews_newsletter_body', array('build' => $build, 'category' => $category, 'language' => 'es', 'simplenews_subscriber' => 'aaa@xxxx.yy'));

  //PREPARE MAIL THEME VARS
  $hook = array(
    'mimemail_message__newsletter_view',
    'mimemail_message__simplenews__newsletter_view',
  );

  $variables = array(
    'module' => 'simplenews',
    'key' => 'newsletter_view',
    'recipient' => 'empty',
    'subject' => $node->title,
    'body' => $body
  );

  //RENDER WITH MAIL THEME PAGE
  $body = theme($hook, $variables);

  print $body;

  return;
}

/*
function dge_newsletter_mail_alter(&$message) {
  if ($message['module'] == 'dge_newsletter' &&
      ($message['key'] == 'subscribe' || $message['key'] == 'unsubscribe') &&
      variable_get('dge_newsletter_sympa_alter_mail_headers', 0) &&
      variable_get('dge_newsletter_sympa_mail_box')) {
    $message['headers']['Sender'] = variable_get('dge_newsletter_sympa_from');
    $message['headers']['From'] = variable_get('dge_newsletter_sympa_from');
    $message['headers']['Return-Path'] = variable_get('dge_newsletter_sympa_from');
    $message['headers']['Errors-To'] = variable_get('dge_newsletter_sympa_from');
  }
}*/


/***********************************************************************/
/*****                     Plantilla en portal                     *****/
/***********************************************************************/

/**
 * Implements hook_theme().
 */
 function dge_newsletter_theme() {
  $path = drupal_get_path('module', 'dge_newsletter') . '/theme';
  return array(
    'dge_newsletter_web_template' => array(
      'template' => 'dge_newsletter_web',
      'path' => $path,
      'variables' => array(
        'newsletter' => NULL
      ),
    ),
    'dge_sendinblue_block' => array(
      'template' => 'dge_sendinblue_block',
      'path' => $path,
      'variables' => array(),
    )
  );
}

/**
 * Implements hook_block_info().
 */
 function dge_newsletter_block_info() {

  $blocks["dge_newsletter_template"] = array(
    'info' => t('DGE Newsletter template'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks["dge_newsletter_draft_template"] = array(
    'info' => t('DGE Newsletter draft template'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['dge_sendinblue_footer'] = array(
    'info' => t('DGE SendInBlue Block'),
    'description' => t('Block for SendInBlue subscriptions'),
    'region' => 'footer',
    'weight' => 1,
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dge_newsletter_block_view($delta) {
  $variables = array();
  if ($delta == 'dge_newsletter_template') {
    return array(
      'content' => dge_newsletter_block_template(),
    );
  } elseif ($delta == 'dge_newsletter_draft_template') {
    return array(
      'content' => dge_newsletter_block_draft_template(),
    );
  } elseif ($delta == 'dge_sendinblue_footer') {
    return array(
      'content' => theme('dge_sendinblue_block', $variables),
    );
  }
}

function dge_newsletter_block_template() {
  $node = menu_get_object();

  return dge_newsletter_node_template($node);
}

function dge_newsletter_block_draft_template() {
  $node = menu_get_object();
  if (module_exists('workbench_moderation')) {
     $node = workbench_moderation_node_current_load($node);
  }

  return dge_newsletter_node_template($node);
}

function dge_newsletter_node_template($node){
  if (!empty($node) && $node->type == 'bulletin') {
    return theme('dge_newsletter_web_template',
      array(
        'newsletter' => $node
    ));
  }

  return "";
}

