<?php

/**
 * Copyright (C) 2017 Entidad Pública Empresarial Red.es
 * 
 * This file is part of "dge_newsletter (datos.gob.es)".
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
* Implements hook_menu().
*/
function dge_newsletter_menu() {
  $items['admin/config/dge/newsletter'] = array(
   'title' => t('Newsletters and sympa settings'),
   'page callback' => 'drupal_get_form',
   'page arguments' => array('dge_newsletter_admin_settings'),
   'access arguments' => array('administer simplenews settings'),
   'type' => MENU_NORMAL_ITEM,
   'file' => 'dge_newsletter.admin.inc',
  );
  $items['boletines/%/mail-view'] = array(
    'title' => t('Newsletter'),
    'page callback' => 'dge_newsletter_mail_presentation',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

 /**
 * Implements hook_simplenews_subscribe_user().
 */
function dge_newsletter_simplenews_subscribe_user($subscriber, $subscription) {

	 if (variable_get('dge_newsletter_sympa_mail_box')) {
     watchdog('dge_newsletter', 'SYMPA: Envio de email para suscribir a @user al newsletter',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);

     $params = array(
       'dge_subscriptors' => $subscriber->mail,
     );

     $mail = drupal_mail('dge_newsletter', 'subscribe',
                       variable_get('dge_newsletter_sympa_mail_box'),
                       language_default(),
                       $params,
                       variable_get('dge_newsletter_sympa_email'));

     if ($mail['result'] == FALSE) {
   	   watchdog('dge_newsletter', 'SYMPA: Fallo al incluir al usuario @user a la lista',
             array('@user' => $subscriber->mail), WATCHDOG_ERROR);
     }
   } else {
   	  watchdog('dge_newsletter', 'SYMPA: Sin configurar. No se ha enviado el correo de subscripcion a @user a la lista',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);
   }
}

 /**
 * Implements hook_simplenews_unsubscribe_user().
 */
function dge_newsletter_simplenews_unsubscribe_user($subscriber, $subscription) {

	if (variable_get('dge_newsletter_sympa_mail_box')) {
     watchdog('dge_newsletter', 'SYMPA: Envio de email para dar de baja a @user del newsletter',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);

     $params = array(
       'dge_subscriptors' => $subscriber->mail,
     );
     $mail = drupal_mail('dge_newsletter', 'unsubscribe',
                       variable_get('dge_newsletter_sympa_mail_box'),
                       language_default(),
                       $params,
                       variable_get('dge_newsletter_sympa_email'));

     if ($mail['result'] == FALSE) {
   	   watchdog('dge_newsletter', 'SYMPA: Fallo al eliminar de la lista al usuario @user',
             array('@user' => $subscriber->mail), WATCHDOG_ERROR);
     }
   } else {
   	  watchdog('dge_newsletter', 'SYMPA: Sin configurar. No se ha enviado el correo de baja de @user de la lista',
             array('@user' => $subscriber->mail), WATCHDOG_INFO);
   }

}

function dge_newsletter_mail($key, &$message, $params) {
  switch ($key) {
    case 'subscribe':
      $sympa_command = variable_get('dge_newsletter_sympa_subscription_command',
                       'QUIET ADD suscriptores %email');
      $sympa_command = str_replace('%email', $params['dge_subscriptors'], $sympa_command);
      $message['subject'] = $sympa_command;
      $message['body'][] = $sympa_command;
      break;
    case 'unsubscribe':
      $sympa_command = variable_get('dge_newsletter_sympa_unsubscription_command',
                       'QUIET DEL suscriptores %email');
      $sympa_command = str_replace('%email', $params['dge_subscriptors'], $sympa_command);
      $message['subject'] = $sympa_command;
      $message['body'][] = $sympa_command;
      break;
  }
}

function dge_newsletter_mail_presentation($nid) {

  if (is_numeric($nid)) {
    $node = node_load($nid);
    if ($node && $node->type == 'bulletin') {
      drupal_set_title($node->title);
      $build = node_view($node, 'email_html');
      unset($build['#theme']);
    }
  }

  if (!isset($build)) {
    drupal_not_found();
    exit();
  }


  if (isset($node->field_simplenews_term['es'][0]['tid'])) {
    $category = $node->field_simplenews_term['es'][0]['tid'];
  } elseif (isset($node->field_simplenews_term['und'][0]['tid'])) {
    $category = $node->field_simplenews_term['und'][0]['tid'];
  }
  $category = taxonomy_term_load($category);

  //Generate email
  $body = theme('simplenews_newsletter_body', array('build' => $build, 'category' => $category, 'language' => 'es', 'simplenews_subscriber' => 'aaa@xxxx.yy'));

  //PREPARE MAIL THEME VARS
  $hook = array(
    'mimemail_message__newsletter_view',
    'mimemail_message__simplenews__newsletter_view',
  );

  $variables = array(
    'module' => 'simplenews',
    'key' => 'newsletter_view',
    'recipient' => 'empty',
    'subject' => $node->title,
    'body' => $body
  );

  //RENDER WITH MAIL THEME PAGE
  $body = theme($hook, $variables);

  print $body;

  return;
}


function dge_newsletter_mail_alter(&$message) {
	if ($message['module'] == 'dge_newsletter' &&
	    ($message['key'] == 'subscribe' || $message['key'] == 'unsubscribe') &&
       variable_get('dge_newsletter_sympa_alter_mail_headers', 0) &&
	    variable_get('dge_newsletter_sympa_mail_box')) {
	    	$message['headers']['Sender'] = variable_get('dge_newsletter_sympa_email');
	    	$message['headers']['From'] = variable_get('dge_newsletter_sympa_email');
	    	$message['headers']['Return-Path'] = variable_get('dge_newsletter_sympa_email');
         $message['headers']['Errors-To'] = variable_get('dge_newsletter_sympa_email');
	}
}
